In [1]:
import numpy as np

# Grid size
N = 4
num_states = N * N

# Initialize value function
V = np.zeros((N, N))

# Parameters
gamma = 1.0
theta = 1e-4
reward = -1

# Actions: up, down, left, right
actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

def is_terminal(i, j):
    return i == N - 1 and j == N - 1

while True:
    delta = 0
    V_new = V.copy()

    for i in range(N):
        for j in range(N):

            if is_terminal(i, j):
                continue

            value = 0
            for di, dj in actions:
                ni, nj = i + di, j + dj

                # Boundary handling
                if ni < 0 or ni >= N or nj < 0 or nj >= N:
                    ni, nj = i, j

                value += 0.25 * (reward + gamma * V[ni, nj]) # Bellman Equation

            V_new[i, j] = value
            delta = max(delta, abs(V_new[i, j] - V[i, j]))

    V = V_new

    if delta < theta:
        break

print(V)


[[-59.42367735 -57.42387125 -54.2813141  -51.71012579]
 [-57.42387125 -54.56699476 -49.71029394 -45.13926711]
 [-54.2813141  -49.71029394 -40.85391609 -29.99766609]
 [-51.71012579 -45.13926711 -29.99766609   0.        ]]
